{
 "title": "Flask app Login metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Login Attempts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(login_attempts_total)\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Flask Pod Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"monitoring/flask-login-podmonitor\"})\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login Rate (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(login_attempts_total[1m])\r\n",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Login attempts (Success v/s Failure)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "login_attempts_total", "legendFormat": "{{result}}" }
   ]
  }
 ]
}